name: Build LaTeX
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Github Action for LaTeX
        uses: xu-cheng/latex-action@v2
